---
- name: 'Remove old packages'
  yum:
    state: absent
    name:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-common-latest
      - docker-engine
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate

# uninstall docker-ce and docker-ce-cli if installing docker-ee
- name: 'Remove old packages'
  yum:
    state: absent
    name:
      - docker-ce
      - docker-ce-cli
  when: docker_edition == "ee"

- name: 'Add Docker Repo Key'
  rpm_key:
    key: "{{ docker_repo_url }}/{{ansible_distribution | lower}}/gpg"
    state: present

- name: 'Add Docker Yum Repo'
  yum_repository:
    name: "docker-{{ docker_edition }}"
    description: "Docker {{ docker_edition | upper }} repo"
    file: "docker-{{ docker_edition }}"
    baseurl: "{{ docker_repo_url }}/{{ ansible_distribution | lower}}/$releasever/$basearch/{{ docker_release }}"

- name: 'Remove version lock on docker'
  command: >
    yum versionlock delete docker-{{ docker_edition }}
  args:
    warn: false
  changed_when: false
  failed_when: false

- name: 'Lookup current docker version'
  shell: |
    yum --showduplicates list docker-{{ docker_edition }} \
      | awk '/([0-9]:)?{{ docker_version_search }}/ { print $2 }' \
      {% if docker_allow_rc == false %} | grep -v -e '\.\(beta\|rc\|tp\)[0-9]*\.' \ {%- endif %}
      | sed -e 's/^[0-9]*://' -e 's/\-.*//' \
      | sort \
      | tail -1
  args:
    warn: false
  when: "docker_version_search is defined"
  changed_when: false
  register: docker_version_search_result
  failed_when: "docker_version_search_result.stdout == ''"

- name: 'Save current docker version'
  set_fact:
    docker_version: "{{ docker_version_search_result.stdout }}"
  when: "docker_version_search is defined"

- name: 'Install Docker Package'
  yum:
    state: present
    allow_downgrade: true
    name:
      - docker-{{docker_edition}}{% if docker_version is defined %}-{{docker_version}}{% endif %}

- name: 'Enable version lock on docker'
  command: >
    yum versionlock add docker-{{ docker_edition }}
  args:
    warn: false
  changed_when: false

